### ISSUE TITLE
마크다운 내에서 프로필 카드가 제대로 갱신되지 않는 것 같습니다.

### ISSUE THREAD

**Issue by usernameSplash** [mazassumnida/mazassumnida#17]
제 solved.ac 프로필을 예시로 설명드리도록 하겠습니다.

우선 mini 프로필 카드의 경우 아래와 같이 G5로 잘 확인되고 있습니다.

[![Solved.ac
프로필](http://mazassumnida.wtf/api/mini/generate_badge?boj=leomessi)](https://solved.ac/leomessi)

그런데 v1, v2 프로필 카드의 경우 이전의 내역이 출력되고 있는 것으로 확인되었습니다.

[![Solved.ac
프로필](http://mazassumnida.wtf/api/v2/generate_badge?boj=leomessi)](https://solved.ac/leomessi)

[![Solved.ac
프로필](http://mazassumnida.wtf/api/generate_badge?boj=leomessi)](https://solved.ac/leomessi)

혹시 갱신을 따로 해주어야 하는지 궁금합니다.

감사합니다.

**Comment by usernameSplash** [comment]
api 주소로 직접 접근하면 올바르게 출력되고 있습니다. http://mazassumnida.wtf/api/v2/generate_badge?boj=leomessi

마크다운 등에 게시하였을 때만 이러한 문제가 발생하고 있습니다.

**Comment by mori8** [comment]
안녕하세요, @usernameSplash 님!
Mazassumnida 프로젝트에 관심을 가져주셔서 감사합니다.
뱃지의 캐시를 삭제하여 이미지가 로딩될 때마다 원 서버로 데이터 요청을 보내도록 하여 제보해주신 문제를 해결했습니다.

다만, **이미 한 번 Github에 업로드 된 url에 대해서는 캐시 정책이 바로 변경되지 않아 여전히 갱신될 때까지 1달 가까이 소요되는 문제**가 있습니다.
따라서 `http://mazassumnida.wtf/api/v2/generate_badge?boj=leomessi` 대신 `http://mazassumnida.wtf/api/v2/generate_badge?boj=leomessi&cache=c` 처럼 미사용 파라미터를 넣은 url을 사용하셔야 할 듯 싶습니다. 해당 url을 github markdown 내에서 사용하시면 문제를 해결하실 때마다 반영이 잘 되는 걸 확인하실 수 있습니다.

감사합니다. 🙂

**Comment by usernameSplash** [comment]
감사합니다.
