### ISSUE TITLE
이미지가 엑박으로 뜹니다.

### ISSUE THREAD

**Issue by yooniversal** [mazassumnida/mazassumnida#22]
제 프로필 README에도 그렇고 [mazassumnida README 글](https://github.com/mazassumnida/mazassumnida/blob/master/README.md)에서도 엑박이 뜹니다.<br>
크롬이나 엣지로 해도 그렇고 다른 기기로 확인해봐도 그렇네요😥<br>
[api 주소](http://mazassumnida.wtf/api/v2/generate_badge?boj=caritas1996)로 들어가면 다음과 같은 에러 문구가 뜹니다.<br>
```
Application error
An error occurred in the application and your page could not be served.
If you are the application owner, check your logs for details.
You can do this from the Heroku CLI with the command
...
```
확인 부탁드립니다!

**Comment by mori8** [comment]
안녕하세요, @yooniversal 님!
로그 확인 결과, heroku에서 매달 무료로 제공해주는 dyno hours를 전부 다 소진해서 생긴 문제였습니다. 
free dyno가 갱신되는 내일 오후 쯤에는 문제가 해결될 것 같습니다.

시원하게 해결해드리지 못해서 죄송합니다. 하필 또 오늘이 31일이어서 결제하기도 애매하네요. 😰

**Comment by yooniversal** [comment]
아닙니다! 무료로 덕분에 항상 잘 이용하고 있는데요😄<br>
고생하십니다!

**Comment by mori8** [comment]
해결되었습니다! 😄
