### ISSUE TITLE
solved.ac의 3월 1일 업데이트 이후 정상적으로 출력되지 않는 이슈가 있습니다.

### ISSUE THREAD

**Issue by wookiist** [mazassumnida/mazassumnida#24]
solved.ac의 3월 1일 업데이트 이후 다음 이미지처럼 정상적으로 뱃지가 출력되지 않고 있습니다 🥲
![image](https://user-images.githubusercontent.com/16011260/109454341-5d5da280-7a97-11eb-800e-70395dc5a2b3.png)

해당 이슈에 대응하는 코드를 작성하여 [pull request](https://github.com/mazassumnida/mazassumnida/pull/23) 하였습니다.
리뷰 후 merge 검토 부탁드립니다! 감사합니다 😃

**Comment by wookiist** [comment]
아 바로 반영해주셨네요.
빠른 확인 감사합니다 .🙇🏻‍♂️

**Comment by mori8** [comment]
PR 감사합니다! 😄
