### ISSUE TITLE
이미지가 중간에 위치

### ISSUE THREAD

**Issue by fightnyy** [mazassumnida/mazassumnida#27]
이미지가 왼쪽으로 치우쳐저서 중간에 놓는 방법이 있는지 궁금합니다.
<center>로 감쌓거나 <p align = center>로 감쌓면 이미지가 깨져 혹시 다른 방법이 있을까요?

**Comment by mori8** [comment]
```
<p align="center">
  <img src="http://mazassumnida.wtf/api/v2/generate_badge?boj=ccoco&cache=c">
</p>
```
처럼 p 태그에 `align="center"` 속성 넣어서 감싸주면 가운데 정렬 가능합니다.
<p align="center">
  <img src="http://mazassumnida.wtf/api/v2/generate_badge?boj=ccoco&cache=c">
</p>
