### ISSUE TITLE
서버 다운 이유?

### ISSUE THREAD

**Issue by LimePencil** [mazassumnida/mazassumnida#35]
지금 서버가 다운된거 같습니다. 언제 복구가 될까요?

<img width="632" alt="스크린샷 2021-12-23 오전 12 09 43" src="https://user-images.githubusercontent.com/71117066/147129766-bf5c3aca-c91a-429b-85f9-f90a951b6e50.png">

**Comment by WhiteHyun** [comment]
아직도 고쳐지지 않았네요 ㅜㅜ

**Comment by mori8** [comment]
헤로쿠 무료 dyno를 모두 소진했는데, 제가 지금 컴퓨터를 사용하지 못하는 상황이라 바로 해결하지 못하고 있습니다 😰
내일 중으로 해결하도록 하겠습니다.

**Comment by LimePencil** [comment]
고쳐졌군요 이 이슈는 닫겠습니다
