### ISSUE TITLE
unknown 표시

### ISSUE THREAD

**Issue by yooniversal** [mazassumnida/mazassumnida#39]
README에 있는 solved 프로필도 모두 unknown으로 표시되는데 확인 부탁드립니다!

**Comment by mori8** [comment]
solved.ac 서버에 [문제](https://www.acmicpc.net/board/view/107146)가 발생해서 마자씀니다에도 영향이 있었습니다! 지금은 잘 동작하네요 😃
제보 감사합니다 😸
