### ISSUE TITLE
boj 프로필 카드가 제대로 표시되지 않는 문제

### ISSUE THREAD

**Issue by hunhee98** [mazassumnida/mazassumnida#40]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/113891368/230327275-901dee9e-f74f-405a-87ab-e75ab033862f.png">
mazassumnida 프로젝트 서버 이슈일까요?

**Comment by strawji02** [comment]
Heroku 서버 이슈입니다
빨리 처리해보겠습니다!

**Comment by hunhee98** [comment]
> Heroku 서버 이슈입니다 빨리 처리해보겠습니다!

고생 많으십니다!

**Comment by strawji02** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/26446288/230337850-a92e1f0f-36e5-47af-9c2c-0562b8a4e885.png">
복구된걸로 확인했습니다
